### ISSUE TITLE
请问可以发一下Nacos里的配置文件吗？

### ISSUE THREAD

**Issue by GMorandi** [Cyborg2077/xuecheng-plus#2]
请问可以发一下Nacos里的配置文件吗？

**Comment by Cyborg2077** [comment]
已上传，详情见：[nacos_config.zip](https://github.com/Cyborg2077/xuecheng-plus/blob/master/nacos_config.zip)

**Comment by Cyborg2077** [comment]
> 请问可以发一下Nacos里的配置文件吗？

已上传，详情见：[nacos_config.zip](https://github.com/Cyborg2077/xuecheng-plus/blob/master/nacos_config.zip)
